05/05/2016 05:00:52 PM - INFO - GUI display widget values successfully restored.
05/05/2016 05:00:52 PM - INFO - Turning off sta3800 controller (sta3800_off).
05/05/2016 05:00:52 PM - INFO - Controller turned off successfully.
05/05/2016 05:00:52 PM - INFO - Turning on sta3800 controller (sta3800_setup).
05/05/2016 05:00:52 PM - INFO - Controller turned on successfully.
05/05/2016 05:00:58 PM - INFO - Starting Exposure Stack with imcount 10, exptime 3.0, and filebase /home/lsst/Data/20160426.exp.3.0s.
05/05/2016 05:00:58 PM - ERROR - Executable exp_acq not found. Image not taken.
Traceback (most recent call last):
  File "./ccdctrl-dev-1.py", line 251, in expose
    filename = exposure.stack(mode, filebase, imcount, exptime, start)
  File "/Users/adamsnyder/ccdcontroller/exposure.py", line 126, in stack
    im_acq(mode, filename, time)
  File "/Users/adamsnyder/ccdcontroller/exposure.py", line 110, in im_acq
    "{0}".format(filename)])
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
05/05/2016 05:01:03 PM - INFO - Turning off sta3800 controller (sta3800_off).
05/05/2016 05:01:03 PM - INFO - Controller turned off successfully.
05/05/2016 05:04:08 PM - INFO - GUI display widget values successfully restored.
05/05/2016 05:04:08 PM - INFO - Turning off sta3800 controller (sta3800_off).
05/05/2016 05:04:08 PM - INFO - Controller turned off successfully.
05/05/2016 05:04:08 PM - INFO - Turning on sta3800 controller (sta3800_setup).
05/05/2016 05:04:08 PM - INFO - Controller turned on successfully.
05/05/2016 05:04:14 PM - INFO - Starting 3.0s Exposure image with filebase /home/lsst/Data/20160426.exp.3.0s.
05/05/2016 05:04:14 PM - ERROR - Executable exp_acq not found. Image not taken
Traceback (most recent call last):
  File "./ccdctrl-dev.py", line 222, in expose
    filename = exposure.im_acq(mode, filebase, exptime)
  File "/Users/adamsnyder/ccdcontroller/exposure.py", line 110, in im_acq
    "{0}".format(filename)])
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
05/05/2016 05:04:50 PM - INFO - Turning off sta3800 controller (sta3800_off).
05/05/2016 05:04:50 PM - INFO - Controller turned off successfully.
05/05/2016 05:06:41 PM - INFO - GUI display widget values successfully restored.
05/05/2016 05:06:41 PM - INFO - Turning off sta3800 controller (sta3800_off).
05/05/2016 05:06:41 PM - INFO - Controller turned off successfully.
05/05/2016 05:06:41 PM - INFO - Turning on sta3800 controller (sta3800_setup).
05/05/2016 05:06:41 PM - INFO - Controller turned on successfully.
05/05/2016 05:07:11 PM - INFO - Turning off sta3800 controller (sta3800_off).
05/05/2016 05:07:11 PM - INFO - Controller turned off successfully.
05/05/2016 05:09:36 PM - INFO - GUI display widget values successfully restored.
05/05/2016 05:09:36 PM - INFO - Turning off sta3800 controller (sta3800_off).
05/05/2016 05:09:36 PM - INFO - Controller turned off successfully.
05/05/2016 05:09:36 PM - INFO - Turning on sta3800 controller (sta3800_setup).
05/05/2016 05:09:36 PM - INFO - Controller turned on successfully.
05/05/2016 05:09:54 PM - INFO - Turning off sta3800 controller (sta3800_off).
05/05/2016 05:09:54 PM - INFO - Controller turned off successfully.
05/05/2016 05:13:15 PM - INFO - GUI display widget values successfully restored.
05/05/2016 05:13:15 PM - INFO - Turning off sta3800 controller (sta3800_off).
05/05/2016 05:13:15 PM - INFO - Controller turned off successfully.
05/05/2016 05:13:15 PM - INFO - Turning on sta3800 controller (sta3800_setup).
05/05/2016 05:13:15 PM - INFO - Controller turned on successfully.
05/05/2016 05:13:18 PM - INFO - Starting 3.0s Exposure image with filebase /home/lsst/Data/20160426/preamp.in.exp.3.0s.
05/05/2016 05:13:18 PM - ERROR - Executable exp_acq not found. Image not taken
Traceback (most recent call last):
  File "./ccdctrl-dev.py", line 223, in expose
    filename = exposure.im_acq(mode, filebase, exptime)
  File "/Users/adamsnyder/ccdcontroller/exposure.py", line 110, in im_acq
    "{0}".format(filename)])
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
05/05/2016 05:13:56 PM - INFO - Starting 3.0s Dark image with filebase /home/lsst/Data/20160426/preamp.in.dark.3.0s.
05/05/2016 05:13:56 PM - ERROR - Executable dark_acq not found. Image not taken
Traceback (most recent call last):
  File "./ccdctrl-dev.py", line 223, in expose
    filename = exposure.im_acq(mode, filebase, exptime)
  File "/Users/adamsnyder/ccdcontroller/exposure.py", line 107, in im_acq
    "{0}".format(filename)])
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
05/05/2016 05:14:00 PM - INFO - Turning off sta3800 controller (sta3800_off).
05/05/2016 05:14:00 PM - INFO - Controller turned off successfully.
05/05/2016 05:20:48 PM - INFO - GUI display widget values successfully restored.
05/05/2016 05:20:48 PM - INFO - Turning off sta3800 controller (sta3800_off).
05/05/2016 05:20:48 PM - INFO - Controller turned off successfully.
05/05/2016 05:20:48 PM - INFO - Turning on sta3800 controller (sta3800_setup).
05/05/2016 05:20:48 PM - INFO - Controller turned on successfully.
05/05/2016 05:20:51 PM - INFO - Turning off sta3800 controller (sta3800_off).
05/05/2016 05:20:51 PM - INFO - Controller turned off successfully.
<<<<<<< HEAD
05/09/2016 09:36:09 AM - INFO - GUI display widget values successfully restored.
05/09/2016 09:36:09 AM - INFO - Turning off sta3800 controller (sta3800_off).
05/09/2016 09:36:09 AM - INFO - Controller turned off successfully.
05/09/2016 09:36:09 AM - INFO - Turning on sta3800 controller (sta3800_setup).
05/09/2016 09:36:09 AM - INFO - Controller turned on successfully.
05/09/2016 09:36:21 AM - INFO - Turning off sta3800 controller (sta3800_off).
05/09/2016 09:36:21 AM - INFO - Controller turned off successfully.
05/09/2016 09:59:48 AM - INFO - GUI display widget values successfully restored.
05/09/2016 09:59:48 AM - INFO - Turning off sta3800 controller (sta3800_off).
05/09/2016 09:59:48 AM - INFO - Controller turned off successfully.
05/09/2016 09:59:48 AM - INFO - Turning on sta3800 controller (sta3800_setup).
05/09/2016 09:59:48 AM - INFO - Controller turned on successfully.
05/09/2016 09:59:59 AM - INFO - Starting 3.0s Dark image with filebase /home/lsst/Data/20160426/preamp.in.dark.3.0s.
05/09/2016 09:59:59 AM - ERROR - Executable dark_acq not found. Image not taken
Traceback (most recent call last):
  File "./ccdctrl-dev.py", line 233, in expose
    filename = exposure.im_acq(mode, filebase, exptime)
  File "/Users/adamsnyder/ccdcontroller/exposure.py", line 107, in im_acq
    "{0}".format(filename)])
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
05/09/2016 10:00:05 AM - INFO - Turning off sta3800 controller (sta3800_off).
05/09/2016 10:00:05 AM - INFO - Controller turned off successfully.
05/09/2016 10:01:43 AM - INFO - GUI display widget values successfully restored.
05/09/2016 10:01:43 AM - INFO - Turning off sta3800 controller (sta3800_off).
05/09/2016 10:01:43 AM - INFO - Controller turned off successfully.
05/09/2016 10:01:43 AM - INFO - Turning on sta3800 controller (sta3800_setup).
05/09/2016 10:01:43 AM - INFO - Controller turned on successfully.
05/09/2016 10:01:49 AM - INFO - Turning off sta3800 controller (sta3800_off).
05/09/2016 10:01:49 AM - INFO - Controller turned off successfully.
05/09/2016 10:01:59 AM - INFO - GUI display widget values successfully restored.
05/09/2016 10:01:59 AM - INFO - Turning off sta3800 controller (sta3800_off).
05/09/2016 10:01:59 AM - INFO - Controller turned off successfully.
05/09/2016 10:01:59 AM - INFO - Turning on sta3800 controller (sta3800_setup).
05/09/2016 10:01:59 AM - INFO - Controller turned on successfully.
05/09/2016 10:02:09 AM - INFO - Starting 3.0s Dark image with filebase /home/lsst/Data/20160426/preamp.in.dark.3.0s.
05/09/2016 10:02:09 AM - ERROR - Executable dark_acq not found. Image not taken
Traceback (most recent call last):
  File "./ccdctrl-dev.py", line 233, in expose
    filename = exposure.im_acq(mode, filebase, exptime)
  File "/Users/adamsnyder/ccdcontroller/exposure.py", line 107, in im_acq
    "{0}".format(filename)])
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
05/09/2016 10:04:52 AM - INFO - Turning off sta3800 controller (sta3800_off).
05/09/2016 10:04:52 AM - INFO - Controller turned off successfully.
05/09/2016 10:07:21 AM - INFO - GUI display widget values successfully restored.
05/09/2016 10:07:21 AM - INFO - Turning off sta3800 controller (sta3800_off).
05/09/2016 10:07:21 AM - INFO - Controller turned off successfully.
05/09/2016 10:07:21 AM - INFO - Turning on sta3800 controller (sta3800_setup).
05/09/2016 10:07:21 AM - INFO - Controller turned on successfully.
05/09/2016 10:07:27 AM - INFO - Starting 3.0s Dark image with filebase /home/lsst/Data/20160426/preamp.in.dark.3.0s.
05/09/2016 10:07:32 AM - ERROR - Executable dark_acq not found. Image not taken
Traceback (most recent call last):
  File "./ccdctrl-dev.py", line 234, in expose
    filename = exposure.im_acq(mode, filebase, exptime)
  File "/Users/adamsnyder/ccdcontroller/exposure.py", line 107, in im_acq
    "{0}".format(filename)])
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
05/09/2016 10:07:43 AM - INFO - Starting 3.0s Dark image with filebase /home/lsst/Data/20160426/preamp.in.dark.3.0s.
05/09/2016 10:07:48 AM - ERROR - Executable dark_acq not found. Image not taken
Traceback (most recent call last):
  File "./ccdctrl-dev.py", line 234, in expose
    filename = exposure.im_acq(mode, filebase, exptime)
  File "/Users/adamsnyder/ccdcontroller/exposure.py", line 107, in im_acq
    "{0}".format(filename)])
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
05/09/2016 10:07:55 AM - INFO - Turning off sta3800 controller (sta3800_off).
05/09/2016 10:07:55 AM - INFO - Controller turned off successfully.
05/09/2016 10:10:25 AM - INFO - GUI display widget values successfully restored.
05/09/2016 10:10:25 AM - INFO - Turning off sta3800 controller (sta3800_off).
05/09/2016 10:10:25 AM - INFO - Controller turned off successfully.
05/09/2016 10:10:25 AM - INFO - Turning on sta3800 controller (sta3800_setup).
05/09/2016 10:10:25 AM - INFO - Controller turned on successfully.
05/09/2016 10:10:38 AM - INFO - Turning off sta3800 controller (sta3800_off).
05/09/2016 10:10:38 AM - INFO - Controller turned off successfully.
05/09/2016 11:50:43 AM - INFO - GUI display widget values successfully restored.
05/09/2016 11:50:43 AM - INFO - Turning off sta3800 controller (sta3800_off).
05/09/2016 11:50:43 AM - INFO - Controller turned off successfully.
05/09/2016 11:50:43 AM - INFO - Turning on sta3800 controller (sta3800_setup).
05/09/2016 11:50:43 AM - INFO - Controller turned on successfully.
05/09/2016 11:51:07 AM - INFO - Turning off sta3800 controller (sta3800_off).
05/09/2016 11:51:07 AM - INFO - Controller turned off successfully.
05/09/2016 11:51:11 AM - INFO - GUI display widget values successfully restored.
05/09/2016 11:51:11 AM - INFO - Turning off sta3800 controller (sta3800_off).
05/09/2016 11:51:11 AM - INFO - Controller turned off successfully.
05/09/2016 11:51:11 AM - INFO - Turning on sta3800 controller (sta3800_setup).
05/09/2016 11:51:11 AM - INFO - Controller turned on successfully.
05/09/2016 11:51:22 AM - INFO - Turning off sta3800 controller (sta3800_off).
05/09/2016 11:51:22 AM - INFO - Controller turned off successfully.
05/09/2016 11:56:16 AM - INFO - GUI display widget values successfully restored.
05/09/2016 11:56:16 AM - INFO - Turning off sta3800 controller (sta3800_off).
05/09/2016 11:56:16 AM - INFO - Controller turned off successfully.
05/09/2016 11:56:16 AM - INFO - Turning on sta3800 controller (sta3800_setup).
05/09/2016 11:56:16 AM - INFO - Controller turned on successfully.
05/09/2016 11:56:25 AM - INFO - Turning off sta3800 controller (sta3800_off).
05/09/2016 11:56:25 AM - INFO - Controller turned off successfully.
05/09/2016 11:57:30 AM - INFO - GUI display widget values successfully restored.
05/09/2016 11:57:30 AM - INFO - Turning off sta3800 controller (sta3800_off).
05/09/2016 11:57:30 AM - INFO - Controller turned off successfully.
05/09/2016 11:57:30 AM - INFO - Turning on sta3800 controller (sta3800_setup).
05/09/2016 11:57:31 AM - INFO - Controller turned on successfully.
05/09/2016 11:57:49 AM - INFO - Turning off sta3800 controller (sta3800_off).
05/09/2016 11:57:49 AM - INFO - Controller turned off successfully.
05/10/2016 09:54:32 AM - INFO - GUI display widget values successfully restored.
05/10/2016 09:54:32 AM - INFO - Turning off sta3800 controller (sta3800_off).
05/10/2016 09:54:32 AM - INFO - Controller turned off successfully.
05/10/2016 09:54:32 AM - INFO - Turning on sta3800 controller (sta3800_setup).
05/10/2016 09:54:32 AM - INFO - Controller turned on successfully.
05/10/2016 09:54:42 AM - INFO - Starting 3.0s Dark image with filebase /home/lsst/Data/20160426/preamp.in.dark.3.0s.
05/10/2016 09:54:47 AM - ERROR - Executable dark_acq not found. Image not taken
Traceback (most recent call last):
  File "./ccdctrl-dev.py", line 234, in expose
    filename = exposure.im_acq(mode, filebase, exptime)
  File "/Users/adamsnyder/ccdcontroller/exposure.py", line 107, in im_acq
    "{0}".format(filename)])
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
05/10/2016 09:54:51 AM - INFO - Starting 3.0s Dark image with filebase /home/lsst/Data/20160426/preamp.in.dark.3.0s.
05/10/2016 09:54:56 AM - ERROR - Executable dark_acq not found. Image not taken
Traceback (most recent call last):
  File "./ccdctrl-dev.py", line 234, in expose
    filename = exposure.im_acq(mode, filebase, exptime)
  File "/Users/adamsnyder/ccdcontroller/exposure.py", line 107, in im_acq
    "{0}".format(filename)])
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
05/10/2016 09:55:04 AM - INFO - Turning off sta3800 controller (sta3800_off).
05/10/2016 09:55:04 AM - INFO - Controller turned off successfully.
=======
05/05/2016 05:28:48 PM - INFO - GUI display widget values successfully restored.
05/05/2016 05:28:48 PM - INFO - Turning off sta3800 controller (sta3800_off).
05/05/2016 05:28:52 PM - INFO - Controller turned off successfully.
05/05/2016 05:28:52 PM - INFO - Turning on sta3800 controller (sta3800_setup).
05/05/2016 05:29:00 PM - INFO - Controller turned on successfully.
05/05/2016 05:30:05 PM - INFO - Starting 3.0s Exposure image with filebase /home/lsst/Data/20160426/test.exp.3.0s.
05/05/2016 05:30:13 PM - INFO - Exposure /home/lsst/Data/20160426/test.exp.3.0s.fits finished successfully.
05/05/2016 05:35:26 PM - INFO - Turning off sta3800 controller (sta3800_off).
05/05/2016 05:35:30 PM - INFO - Controller turned off successfully.
>>>>>>> 78614ca79e3715fa1a16fbe00b2b434424e3e345
05/10/2016 10:10:00 AM - INFO - GUI display widget values successfully restored.
05/10/2016 10:10:00 AM - INFO - Turning off sta3800 controller (sta3800_off).
05/10/2016 10:10:00 AM - INFO - Controller turned off successfully.
05/10/2016 10:10:00 AM - INFO - Turning on sta3800 controller (sta3800_setup).
05/10/2016 10:10:00 AM - INFO - Controller turned on successfully.
05/10/2016 10:10:25 AM - INFO - Turning off sta3800 controller (sta3800_off).
05/10/2016 10:10:25 AM - INFO - Controller turned off successfully.
05/10/2016 10:11:53 AM - INFO - GUI display widget values successfully restored.
05/10/2016 10:11:53 AM - INFO - Turning off sta3800 controller (sta3800_off).
05/10/2016 10:11:57 AM - INFO - Controller turned off successfully.
05/10/2016 10:11:57 AM - INFO - Turning on sta3800 controller (sta3800_setup).
05/10/2016 10:12:06 AM - INFO - Controller turned on successfully.
05/10/2016 10:12:25 AM - INFO - Starting 3.0s Exposure image with filebase /home/lsst/Data/20160426/test.exp.3.0s.
05/10/2016 10:13:27 AM - INFO - GUI display widget values successfully restored.
05/10/2016 10:13:27 AM - INFO - Turning off sta3800 controller (sta3800_off).
05/10/2016 10:13:27 AM - INFO - Controller turned off successfully.
05/10/2016 10:13:27 AM - INFO - Turning on sta3800 controller (sta3800_setup).
05/10/2016 10:13:27 AM - INFO - Controller turned on successfully.
05/10/2016 10:13:31 AM - INFO - Starting 3.0s Exposure image with filebase /home/lsst/Data/20160426/test.exp.3.0s.
05/10/2016 10:15:53 AM - INFO - GUI display widget values successfully restored.
05/10/2016 10:15:53 AM - INFO - Turning off sta3800 controller (sta3800_off).
05/10/2016 10:15:53 AM - INFO - Controller turned off successfully.
05/10/2016 10:15:53 AM - INFO - Turning on sta3800 controller (sta3800_setup).
05/10/2016 10:15:53 AM - INFO - Controller turned on successfully.
05/10/2016 10:16:04 AM - INFO - Turning off sta3800 controller (sta3800_off).
05/10/2016 10:16:04 AM - INFO - Controller turned off successfully.
05/10/2016 10:24:33 AM - INFO - GUI display widget values successfully restored.
05/10/2016 10:24:33 AM - INFO - Turning off sta3800 controller (sta3800_off).
05/10/2016 10:24:33 AM - INFO - Controller turned off successfully.
05/10/2016 10:24:33 AM - INFO - Turning on sta3800 controller (sta3800_setup).
05/10/2016 10:24:33 AM - INFO - Controller turned on successfully.
05/10/2016 10:24:35 AM - INFO - Starting 3.0s Exposure image with filebase /home/lsst/Data/20160426/test.exp.3.0s.
05/10/2016 10:24:44 AM - INFO - GUI display widget values successfully restored.
05/10/2016 10:24:44 AM - INFO - Turning off sta3800 controller (sta3800_off).
05/10/2016 10:24:44 AM - INFO - Controller turned off successfully.
05/10/2016 10:24:44 AM - INFO - Turning on sta3800 controller (sta3800_setup).
05/10/2016 10:24:44 AM - INFO - Controller turned on successfully.
05/10/2016 10:24:47 AM - INFO - Starting 3.0s Exposure image with filebase /home/lsst/Data/20160426/test.exp.3.0s.
05/10/2016 10:27:07 AM - INFO - GUI display widget values successfully restored.
05/10/2016 10:27:07 AM - INFO - Turning off sta3800 controller (sta3800_off).
05/10/2016 10:27:07 AM - INFO - Controller turned off successfully.
05/10/2016 10:27:07 AM - INFO - Turning on sta3800 controller (sta3800_setup).
05/10/2016 10:27:07 AM - INFO - Controller turned on successfully.
05/10/2016 10:28:59 AM - INFO - GUI display widget values successfully restored.
05/10/2016 10:28:59 AM - INFO - Turning off sta3800 controller (sta3800_off).
05/10/2016 10:28:59 AM - INFO - Controller turned off successfully.
05/10/2016 10:28:59 AM - INFO - Turning on sta3800 controller (sta3800_setup).
05/10/2016 10:28:59 AM - INFO - Controller turned on successfully.
05/10/2016 10:29:02 AM - ERROR - File already exits. Image not taken.
Traceback (most recent call last):
  File "./ccdctrl-dev.py", line 233, in expose
    filename = exposure.im_acq(mode, filebase, exptime)
  File "/home/lsst/ccdcontroller/exposure.py", line 99, in im_acq
    raise IOError
IOError
05/10/2016 10:29:09 AM - ERROR - File already exits. Image not taken.
Traceback (most recent call last):
  File "./ccdctrl-dev.py", line 233, in expose
    filename = exposure.im_acq(mode, filebase, exptime)
  File "/home/lsst/ccdcontroller/exposure.py", line 99, in im_acq
    raise IOError
IOError
05/10/2016 10:29:13 AM - INFO - Turning off sta3800 controller (sta3800_off).
05/10/2016 10:29:13 AM - INFO - Controller turned off successfully.
05/10/2016 10:30:01 AM - INFO - GUI display widget values successfully restored.
05/10/2016 10:30:01 AM - INFO - Turning off sta3800 controller (sta3800_off).
05/10/2016 10:30:01 AM - INFO - Controller turned off successfully.
05/10/2016 10:30:01 AM - INFO - Turning on sta3800 controller (sta3800_setup).
05/10/2016 10:30:01 AM - INFO - Controller turned on successfully.
05/10/2016 10:30:04 AM - INFO - Starting 3.0s Exposure image with filebase /home/lsst/Data/20160426/test.exp.3.0s.
05/10/2016 10:30:04 AM - ERROR - File already exits. Image not taken.
Traceback (most recent call last):
  File "./ccdctrl-dev.py", line 232, in expose
    filename = exposure.im_acq(mode, filebase, exptime)
  File "/home/lsst/ccdcontroller/exposure.py", line 99, in im_acq
    raise IOError
IOError
05/10/2016 10:30:27 AM - INFO - Turning off sta3800 controller (sta3800_off).
05/10/2016 10:30:27 AM - INFO - Controller turned off successfully.
05/10/2016 10:31:27 AM - INFO - GUI display widget values successfully restored.
05/10/2016 10:31:27 AM - INFO - Turning off sta3800 controller (sta3800_off).
05/10/2016 10:31:31 AM - INFO - Controller turned off successfully.
05/10/2016 10:31:31 AM - INFO - Turning on sta3800 controller (sta3800_setup).
05/10/2016 10:31:39 AM - INFO - Controller turned on successfully.
05/10/2016 10:32:15 AM - INFO - Starting 3.0s Exposure image with filebase /home/lsst/Data/20160426/test.exp.3.0s.
05/10/2016 10:32:15 AM - ERROR - File already exits. Image not taken.
Traceback (most recent call last):
  File "./ccdctrl.py", line 232, in expose
    filename = exposure.im_acq(mode, filebase, exptime)
  File "/home/lsst/ccdcontroller/exposure.py", line 99, in im_acq
    raise IOError
IOError
05/10/2016 10:32:26 AM - INFO - Starting 5.0s Exposure image with filebase /home/lsst/Data/20160426/test.exp.5.0s.
05/10/2016 10:32:56 AM - INFO - Exposure /home/lsst/Data/20160426/test.exp.5.0s.fits finished successfully.
05/10/2016 10:33:12 AM - INFO - Turning off sta3800 controller (sta3800_off).
05/10/2016 10:33:16 AM - INFO - Controller turned off successfully.
05/10/2016 04:15:48 PM - INFO - GUI display widget values successfully restored.
05/10/2016 04:15:48 PM - INFO - Turning off sta3800 controller (sta3800_off).
05/10/2016 04:15:52 PM - INFO - Controller turned off successfully.
05/10/2016 04:15:52 PM - INFO - Turning on sta3800 controller (sta3800_setup).
05/10/2016 04:16:01 PM - INFO - Controller turned on successfully.
05/10/2016 04:17:46 PM - INFO - Data directory changed to /home/lsst/Data/20160510.
05/10/2016 04:18:16 PM - INFO - Turning off sta3800 controller (sta3800_off).
05/10/2016 04:18:20 PM - INFO - Controller turned off successfully.
05/10/2016 04:22:49 PM - INFO - GUI display widget values successfully restored.
05/10/2016 04:22:49 PM - INFO - Turning off sta3800 controller (sta3800_off).
05/10/2016 04:22:53 PM - INFO - Controller turned off successfully.
05/10/2016 04:22:53 PM - INFO - Turning on sta3800 controller (sta3800_setup).
05/10/2016 04:23:01 PM - INFO - Controller turned on successfully.
05/10/2016 04:28:59 PM - INFO - Data directory changed to /home/lsst/Data/20160510.
05/10/2016 04:29:10 PM - INFO - Starting 5.0s Exposure image with filebase /home/lsst/Data/20160510/.exp.5.0s.
05/10/2016 04:29:34 PM - INFO - Exposure /home/lsst/Data/20160510/.exp.5.0s.fits finished successfully.
05/10/2016 04:40:07 PM - INFO - Starting 5.0s Exposure image with filebase /home/lsst/Data/20160510/.exp.5.0s.
05/10/2016 04:40:07 PM - ERROR - File already exits. Image not taken.
Traceback (most recent call last):
  File "./ccdctrl.py", line 232, in expose
    filename = exposure.im_acq(mode, filebase, exptime)
  File "/home/lsst/ccdcontroller/exposure.py", line 99, in im_acq
    raise IOError
IOError
05/10/2016 04:42:03 PM - INFO - Starting 3.0s Exposure image with filebase /home/lsst/Data/20160510/.exp.3.0s.
05/10/2016 04:42:33 PM - INFO - Exposure /home/lsst/Data/20160510/.exp.3.0s.fits finished successfully.
05/10/2016 04:44:51 PM - INFO - Turning off sta3800 controller (sta3800_off).
05/10/2016 04:44:55 PM - INFO - Controller turned off successfully.
05/10/2016 04:55:20 PM - INFO - GUI display widget values successfully restored.
05/10/2016 04:55:20 PM - INFO - Turning off sta3800 controller (sta3800_off).
05/10/2016 04:55:24 PM - INFO - Controller turned off successfully.
05/10/2016 04:55:24 PM - INFO - Turning on sta3800 controller (sta3800_setup).
05/10/2016 04:55:32 PM - INFO - Controller turned on successfully.
05/10/2016 04:55:38 PM - INFO - Starting 3.0s Exposure image with filebase /home/lsst/Data/20160510/test.exp.3.0s.
05/10/2016 04:56:11 PM - INFO - Exposure /home/lsst/Data/20160510/test.exp.3.0s.10.fits finished successfully.
05/10/2016 04:56:42 PM - INFO - Turning off sta3800 controller (sta3800_off).
05/10/2016 04:56:46 PM - INFO - Controller turned off successfully.
05/10/2016 04:58:53 PM - INFO - GUI display widget values successfully restored.
05/10/2016 04:58:53 PM - INFO - Turning off sta3800 controller (sta3800_off).
05/10/2016 04:58:57 PM - INFO - Controller turned off successfully.
05/10/2016 04:58:57 PM - INFO - Turning on sta3800 controller (sta3800_setup).
05/10/2016 04:59:05 PM - INFO - Controller turned on successfully.
05/10/2016 05:02:24 PM - INFO - Data directory changed to /home/lsst/Data/dkg.4.29.15.
05/10/2016 05:04:05 PM - INFO - Data directory changed to /home/lsst/Data/20160510.
05/10/2016 05:06:51 PM - INFO - Starting 5.0s Exposure image with filebase /home/lsst/Data/20160510/kg.test.exp.5.0s.
05/10/2016 05:07:01 PM - INFO - Exposure /home/lsst/Data/20160510/kg.test.exp.5.0s.100.fits finished successfully.
05/10/2016 05:55:37 PM - INFO - Turning off sta3800 controller (sta3800_off).
05/10/2016 05:55:42 PM - INFO - Controller turned off successfully.
